FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
COPY --from=build /app/ormconfig.ts ./ormconfig.ts
COPY --from=build /app/ormconfig.cjs ./ormconfig.cjs
COPY --from=build /app/assets ./assets
EXPOSE 3000
CMD ["node", "dist/src/main.js"]
